# Generated by Django 3.2 on 2023-03-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Identificador')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bread', verbose_name='Imagem')),
                ('weight', models.PositiveIntegerField(verbose_name='Peso em Kg')),
            ],
            options={
                'verbose_name': 'Pão',
                'verbose_name_plural': 'Pães',
            },
        ),
    ]
