# Generated by Django 3.2 on 2023-03-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatity', models.PositiveSmallIntegerField(verbose_name='Quatidade')),
                ('price_sum', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sub Total')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bread', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item de venda',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço Total')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('customer_phone_number', models.CharField(max_length=11, verbose_name='Telefone do Cliente')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.saleitem', verbose_name='items')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='Campaing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(verbose_name='Data de Entrega')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Identificador')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sale', verbose_name='Vendas')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
            },
        ),
    ]
