# Generated by Django 3.2 on 2023-03-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campaing_sale_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaing',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Entrega'),
        ),
    ]
