# Generated by Django 3.2 on 2023-03-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_campaing_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaing',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Identificador'),
        ),
    ]
