# Generated by Django 3.2 on 2023-03-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230317_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='campaing',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
    ]
