# Generated by Django 3.2 on 2023-03-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230317_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Peso em Kg'),
        ),
    ]
