# Generated by Django 3.2 on 2023-06-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bread_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, verbose_name='Nome de Usuario')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do post')),
                ('post_id', models.CharField(max_length=100, verbose_name='Id do post')),
                ('rewarded', models.BooleanField(default=False, verbose_name='Recompensado')),
                ('rewarded_date', models.DateTimeField(blank=True, verbose_name='Data da recompensa')),
            ],
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
