# Generated by Django 3.2 on 2023-06-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_instagramuser_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='rewarded_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da recompensa'),
        ),
    ]
